### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by ita1024** [Rudd-O/zfs-fedora-installer#13]
Thanks for sharing this!

Two things are not mentioned in the docs - https://rudd-o.com/linux-and-free-software/installing-fedora-on-top-of-zfs

1. libblkid-devel and libattr-devel seem to be required dependencies on Fedora 23 (build error)
2. The rsync command requires additional -A and -X options to have Selinux working properly

**Comment by Rudd-O** [comment]
You're right.  I have added libattr and libblkid to the docs now.  I have added the AX options to rsync.

Thanks.

**Comment by Rudd-O** [comment]
I need help from you in one sense:

deploy-zfs... can I see the error in question?

**Comment by Rudd-O** [comment]
I repro'd the issue.  No worries.
