### ISSUE TITLE
docs - install kernel-devel

### ISSUE THREAD

**Issue by ita1024** [Rudd-O/zfs-fedora-installer#15]
Make a fresh Fedora server installation, update the system with "yum update", reboot to use the new kernel, then run deploy-zfs.

The zfs.ko module is not installed:
https://waf.io/fedora_zfs_installer_error.png

As a workaround, I tried to remove a few rpms and run deploy-zfs again to see what was executed, but then the spl build would just hang.

I finally found the packages to remove with:
rpm -e zfs zfs-dkms zfs-dracut libzpool2 libzfs2-devel libzfs2 zfs-dkms spl-dkms spl

Then I ran "yum install kernel-devel libselinux-devel parted lsscsi wget" as listed on the zfsonlinux page, and run deploy-zfs again and it finally worked.

**Comment by ita1024** [comment]
I cannot reproduce the problem for some reason. It must have been a user error.

**Comment by Rudd-O** [comment]
You updated the system with yum-update.  This installed a new kernel version, but for some reason the ZFS kernel module wasn't built.

If you are going to try to update the system, do it before the install of ZFS.  Normal updates don't have any problem, BUT if you do it while you are in the middle of installing ZFS.

This is why the instructions in my guide explicitly say "reboot with the exact kernel you had before you installed ZFS".
