### ISSUE TITLE
deploy-zfs: NameError: global name 'do_cleanup' is not defined

### ISSUE THREAD

**Issue by fb87** [Rudd-O/zfs-fedora-installer#17]
This is the output message of completely new Fedora 23 and 24 beta installation (image of 06.06.2016):

INFO:root:deploy_zfs_in_machine@1371	Checking if grub-zfs-fixer has the GRUB ZFS fixer installed
   DEBUG:root:        check_output@ 158	Check outputting rpm -q grub-zfs-fixer-0.0.3-1 in cwd '/home/frank'
   DEBUG:root:        check_output@ 162	First line of output from command: grub-zfs-fixer-0.0.3-1.noarch
    INFO:root:deploy_zfs_in_machine@1458	Checking if keystone packages spl, spl-dkms are installed
   DEBUG:root:          check_call@ 152	Check calling rpm -q spl spl-dkms in cwd '/home/frank'
    INFO:root:deploy_zfs_in_machine@1458	Checking if keystone packages zfs, zfs-dkms, zfs-dracut are installed
   DEBUG:root:          check_call@ 152	Check calling rpm -q zfs zfs-dkms zfs-dracut in cwd '/home/frank'
   ERROR:root:          deploy_zfs@1535	Unexpected error
Traceback (most recent call last):
  File "/usr/src/zfs-fedora-installer/src/installfedoraonzfs/__init__.py", line 1533, in deploy_zfs
    to_unmount=to_unmount,)
  File "/usr/src/zfs-fedora-installer/src/installfedoraonzfs/__init__.py", line 1503, in deploy_zfs_in_machine
    raise ZFSBuildFailure("expected to find but could not find module zfs.ko in %s.  Perhaps the ZFS source you used is too old to work with the kernel this program installed?" % modules_dir)
ZFSBuildFailure: expected to find but could not find module zfs.ko in /usr/lib/modules/*/*/zfs.ko.  Perhaps the ZFS source you used is too old to work with the kernel this program installed?
Traceback (most recent call last):
  File "/usr/src/zfs-fedora-installer/deploy-zfs", line 10, in <module>
    sys.exit(installfedoraonzfs.deploy_zfs())
  File "/usr/src/zfs-fedora-installer/src/installfedoraonzfs/__init__.py", line 1536, in deploy_zfs
    if do_cleanup:
NameError: global name 'do_cleanup' is not defined

**Comment by Rudd-O** [comment]
Looks like a legit bug.  Sorry for the lateness, attempting to fix.

**Comment by Rudd-O** [comment]
Issue fixed.  Thanks for the report!
