### ISSUE TITLE
efi

### ISSUE THREAD

**Issue by digrouz** [Rudd-O/zfs-fedora-installer#21]
Hi,

Is the resulting image booting on a computer in efi boot ?

Kind Regards

**Comment by Rudd-O** [comment]
Not to my knowledge, but I am happy to add support for it.  Send me the code and I will merge it.

On March 24, 2017 12:32:00 PM GMT+01:00, Nicolas Di Gregorio <notifications@github.com> wrote:
>Hi,
>
>Is the resulting image booting on a computer in efi boot ?
>
>Kind Regards
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Rudd-O/zfs-fedora-installer/issues/21

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Rudd-O** [comment]
I am worklng on adding support for EFI.  We'll see how that works out.

**Comment by Rudd-O** [comment]
Can you please test if the resultant image boots via EFI now?  Preemptively closing it, but you can comment if it does not work, so I can reopen the issue.
