### ISSUE TITLE
SELinux

### ISSUE THREAD

**Issue by pfandl** [Rudd-O/zfs-fedora-installer#22]
It seems that this is sufficient to get SELinux to work with Fedora Server 25:

`zfs set xattr=sa pool`

I had some errors in syncing into the chroot and therefore needed to create following directories: (i did it in the emergency console after a reboot but it should be fine within the chroot i guess)

```
mkdir /var/lib/dbus
mkdir /var/log/audit
```

Thanks for the tutorial! cheers

**Comment by Rudd-O** [comment]
This is going to be fixed as soon as I test staging and merge into master.
