### ISSUE TITLE
zfs repo not working with fedora 31

### ISSUE THREAD

**Issue by fneddy** [Rudd-O/zfs-fedora-installer#33]
your [zfs repo](https://github.com/Rudd-O/zfs) seems to not work with the newest f31 release.
If i change the repo url to [the native repo](https://github.com/zfsonlinux/zfs) it successfully compiles the zfs modules.

maybe consider updating your zfs repo or change (line 1416 in __init__.py](https://github.com/Rudd-O/zfs-fedora-installer/blob/625f1814653ae477024d8ecc9c139f2a7ed2d832/src/installfedoraonzfs/__init__.py#L1416)  to use the official repo

**Comment by fneddy** [comment]
maybe you should consider using the ["official" fedora zfs repo](https://github.com/zfsonlinux/zfs/wiki/Fedora)

**Comment by Rudd-O** [comment]
Working on fixing it...

**Comment by Rudd-O** [comment]
The `staging` branch should have something that works correctly.  Will merge to `master` soon.  Testing the final details.
