### ISSUE TITLE
zpool not being exported at reboots

### ISSUE THREAD

**Issue by seriv** [Rudd-O/zfs-fedora-installer#5]
Both qemu and copied to physical drives fedora rooted on zfs installations require 2 reboots each time. First reboot fails with 
```
cannot import 'rpool': pool may be in use from other system
```
many times until it drops into emergency shell. There you can import zpool with '-f' and then export it and reboot without giving machine a chance to retry importing zpool. Then next boot will succeed.

**Comment by Rudd-O** [comment]
Is this still an issue?
