### ISSUE TITLE
Script fails with Device 'ide-hd' could not be initialized

### ISSUE THREAD

**Issue by bra-fsn** [Rudd-O/zfs-fedora-installer#7]
I run the script (up to date ATM) with:
./install-fedora-on-zfs  --separate-boot boot.img --host-name finestra --luks-password PASS --releasever 20 volume.img
and get this error in the end:
DEBUG:root:Check calling 'losetup' '-d' '/dev/loop0' in cwd '/usr/src/zfs-fedora-installer'
DEBUG:root:Check calling 'losetup' '-d' '/dev/loop1' in cwd '/usr/src/zfs-fedora-installer'
DEBUG:root:Check calling 'qemu-kvm' '-nographic' '-serial' '/dev/stdout' '-name' 'finestra' '-M' 'pc-1.2' '-no-reboot' '-m' '1024' '-uuid' '27484500-7e79-11e3-839e-f0def1e14563' '-kernel' '/dev/shm/tmph91QfC/vmlinuz-3.12.7-300.fc20.x86_64' '-initrd' '/dev/shm/tmph91QfC/initramfs-3.12.7-300.fc20.x86_64.img' '-append' 'rd.luks.uuid=8e55840e-7d18-43f1-ae18-b6dd7317e7e3 rd.luks.key=/key console=ttyS0 root=ZFS=tank/ROOT/os ro init=/installbootloader' '-enable-kvm' '-drive' 'file=boot.img,if=none,id=drive-ide0-0-0,format=raw' '-device' 'ide-hd,bus=ide.0,unit=0,drive=drive-ide0-0-0,id=ide0-0-0,bootindex=1' '-drive' 'file=volume.img,if=none,id=drive-ide0-1-0,format=raw' '-device' 'ide-hd,bus=ide.1,unit=0,drive=drive-ide0-1-0,id=ide0-1-0,bootindex=2' '-drive' 'file=/dev/shm/tmph91QfC/keydev.img,if=none,id=drive-ide1-0-0,format=raw' '-device' 'ide-hd,bus=ide.1,unit=0,drive=drive-ide1-0-0,id=ide1-0-0,bootindex=3' in cwd '/usr/src/zfs-fedora-installer'
QEMU 1.6.1 monitor - type 'help' for more information
(qemu) qemu-system-x86_64: -device ide-hd,bus=ide.1,unit=0,drive=drive-ide1-0-0,id=ide1-0-0,bootindex=3: IDE unit 0 is in use
qemu-system-x86_64: -device ide-hd,bus=ide.1,unit=0,drive=drive-ide1-0-0,id=ide1-0-0,bootindex=3: Device initialization failed.
qemu-system-x86_64: -device ide-hd,bus=ide.1,unit=0,drive=drive-ide1-0-0,id=ide1-0-0,bootindex=3: Device 'ide-hd' could not be initialized
Traceback (most recent call last):
  File "./install-fedora-on-zfs", line 796, in <module>
    sys.exit(main())
  File "./install-fedora-on-zfs", line 788, in main
    args.luksoptions,
  File "./install-fedora-on-zfs", line 725, in install_fedora
    check_call(cmd)
  File "./install-fedora-on-zfs", line 82, in check_call
    return subprocess.check_call(*args,**kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['qemu-kvm', '-nographic', '-serial', '/dev/stdout', '-name', 'finestra', '-M', 'pc-1.2', '-no-reboot', '-m', '1024', '-uuid', '27484500-7e79-11e3-839e-f0def1e14563', '-kernel', '/dev/shm/tmph91QfC/vmlinuz-3.12.7-300.fc20.x86_64', '-initrd', '/dev/shm/tmph91QfC/initramfs-3.12.7-300.fc20.x86_64.img', '-append', 'rd.luks.uuid=8e55840e-7d18-43f1-ae18-b6dd7317e7e3 rd.luks.key=/key console=ttyS0 root=ZFS=tank/ROOT/os ro init=/installbootloader', '-enable-kvm', '-drive', 'file=boot.img,if=none,id=drive-ide0-0-0,format=raw', '-device', 'ide-hd,bus=ide.0,unit=0,drive=drive-ide0-0-0,id=ide0-0-0,bootindex=1', '-drive', 'file=volume.img,if=none,id=drive-ide0-1-0,format=raw', '-device', 'ide-hd,bus=ide.1,unit=0,drive=drive-ide0-1-0,id=ide0-1-0,bootindex=2', '-drive', 'file=/dev/shm/tmph91QfC/keydev.img,if=none,id=drive-ide1-0-0,format=raw', '-device', 'ide-hd,bus=ide.1,unit=0,drive=drive-ide1-0-0,id=ide1-0-0,bootindex=3']' returned non-zero exit status 1

This is on a fedora 20 default install.

**Comment by Rudd-O** [comment]
Please message me again if you can still repro the issue.  It's been two years and I cannot reproduce it.
