### ISSUE TITLE
Script does not work with Fedora 22 and dnf

### ISSUE THREAD

**Issue by appletalk** [Rudd-O/zfs-fedora-installer#8]
When the script is run on Fedora 21 installing Fedora 22 the script fails.

Run with this command.
sudo ./install-fedora-on-zfs --pool-name rpool --host-name localhost.localdomain --root-password root --swap-size 512 --luks-password luks --releasever 22 /dev/sda

Error message.
DEBUG:root:Check calling chroot /mnt/rpool yum install -y -c /tmp/tmpXRC4E5 -- rpm-build tar gzip
Yum command has been deprecated, redirecting to '/usr/bin/dnf install -y -c /tmp/tmpXRC4E5 -- rpm-build tar gzip'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'

Fedora 22 - x86_64                        1.0 MB/s |  41 MB     00:40    
Fedora 22 - x86_64 - Updates              622 kB/s | 7.6 MB     00:12    
Last metadata expiration check performed 0:00:08 ago on Tue Jun 16 05:38:26 2015.
No package -- available.
Error: no package matched: --
Unexpected error: Command '['chroot', '/mnt/rpool', 'yum', 'install', '-y', '-c', '/tmp/tmpXRC4E5', '--', 'rpm-build', 'tar', 'gzip']' returned non-zero exit status 1
Cleaning up now

**Comment by Rudd-O** [comment]
This is a bug in DNF -- double dash should be accepted as a parameter ending option processing.  Please report upstream.
